name: Liquibase Validation

on:
  pull_request:
    branches:
      - develop
      - staging
      - main
    paths:
      - 'changelog/**'

jobs:
  liquibase-validate:
    name: Validate Liquibase Changelogs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Validate Liquibase Changelogs
        run: mvn liquibase:validate
